name: "WASI: Install additional prerequisites"
inputs:
  wasi_sdk_version:
    required: true
  wasmtime_version:
    required: true
runs:
  using: composite
  steps:
    - name: "Linux: Install wasi-sdk"
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -eux
        cd ..

        WASI_SDK_VERSION='${{ inputs.wasi_sdk_version }}'
        curl -OL https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-${WASI_SDK_VERSION}/wasi-sdk-${WASI_SDK_VERSION}.0-x86_64-linux.tar.gz
        tar -xzf wasi-sdk-${WASI_SDK_VERSION}.0-x86_64-linux.tar.gz
        mv wasi-sdk-${WASI_SDK_VERSION}.0-x86_64-linux wasi-sdk
    - name: "Linux: Install wasmtime"
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -eux
        cd ..

        WASMTIME_VERSION='${{ inputs.wasmtime_version }}'
        curl -OL https://github.com/bytecodealliance/wasmtime/releases/download/v${WASMTIME_VERSION}/wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz
        tar -xf wasmtime-v${WASMTIME_VERSION}-x86_64-linux.tar.xz
        mv wasmtime-v${WASMTIME_VERSION}-x86_64-linux wasmtime
