name: "WASI: Install additional prerequisites"
inputs:
  wasi_sdk_version:
    required: false
    default: 34
  wasmtime_version:
    required: false
    default: 48.0.1
runs:
  using: composite
  steps:
    - name: "Install wasi-sdk"
      uses: bytecodealliance/setup-wasi-sdk-action@v1
      with:
        add-to-path: false
        version: ${{ inputs.wasi_sdk_version }}

    - name: "Install wasmtime"
      uses: bytecodealliance/actions/wasmtime/setup@v1
      with:
        version: ${{ inputs.wasmtime_version }}
