name: Upload to GitHub
runs:
  using: composite
  steps:

    - name: Download all artifacts
      uses: actions/download-artifact@v8
      with:
        path: artifacts/
        merge-multiple: true # place all files into artifacts/ directly

    - name: Set GITHUB_RELEASE_TAG & ARTIFACT_ID
      shell: bash
      run: |
        set -eux
        if [[ '${{ github.ref }}' = refs/tags/v* ]]; then
          tag='${{ github.ref }}'
          tag="${tag:10}"
          artifactID="${tag:1}"
        else
          tag=CI
          artifactID='${{ github.sha }}'
          artifactID="${artifactID:0:8}"
        fi
        echo "GITHUB_RELEASE_TAG=$tag" >> $GITHUB_ENV
        echo "ARTIFACT_ID=$artifactID" >> $GITHUB_ENV

    - name: Compute hashes
      shell: bash
      run: |
        set -eux

        cd artifacts
        ls -lh
        sha256sum * > "ldc2-$ARTIFACT_ID.sha256sums.txt"

    - name: Upload to GitHub release
      uses: ncipollo/release-action@v1
      with:
        tag: ${{ env.GITHUB_RELEASE_TAG }}
        artifacts: artifacts/*
        allowUpdates: true
        artifactErrorsFailBuild: true
        prerelease: true
        omitPrereleaseDuringUpdate: true
        omitName: true
        omitBody: true
        omitDraftDuringUpdate: true
        # master builds: remove existing artifacts for 'CI' release
        removeArtifacts: ${{ env.GITHUB_RELEASE_TAG == 'CI' }}
