name: 'macOS: Cross-compile iOS libraries, copy to install dir & extend ldc2.conf'
inputs:
  arch:
    required: true
  ios_deployment_target:
    required: false
    default: '12.0'
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -eux
        cd ..

        arch='${{ inputs.arch }}'
        deployment_target='${{ inputs.ios_deployment_target }}'
        if [[ "$arch" == arm64 ]]; then
            triples=("$arch-apple-ios$deployment_target" "$arch-apple-ios$deployment_target-simulator")
            sysroot=('/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk' '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk')
        else
            triples=("$arch-apple-ios$deployment_target-simulator")
            sysroot=('/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk')
        fi


        for i in "${!triples[@]}"; do
        reg=''
        simulator=''
        
        if [[ $i == 1 ]]; then
          reg='.*-simulator'
          simulator='-simulator'
        fi
        
        installed/bin/ldc-build-runtime --ninja \
          --dFlags="-mtriple=${triples[$i]}" \
          --ldcSrcDir="$PWD/ldc" \
          --installWithSuffix="-ios-$arch" \
          CMAKE_SYSTEM_NAME=iOS \
          CMAKE_OSX_SYSROOT="${sysroot[$i]}" \
          CMAKE_OSX_ARCHITECTURES="$arch" \
          CMAKE_OSX_DEPLOYMENT_TARGET="$deployment_target" \
          BUILD_LTO_LIBS=ON

        section="
        \"$arch-apple-ios$reg\":
        {
            switches ~= [
                \"-Xcc=-isysroot\",
                \"-Xcc=${sysroot[$i]}\",
            ];
            lib-dirs = [
                \"%%ldcbinarypath%%/../lib-ios-$arch$simulator\",
            ];
            rpath = \"%%ldcbinarypath%%/../lib-ios-$arch$simulator\";
        };"
        echo "$section" >> installed/etc/ldc2.conf
        cat installed/etc/ldc2.conf

        done
