name: Run LDC D unittests
inputs:
  shell:
    required: false
    default: bash
runs:
  using: composite
  steps:
    - run: cd ../build && ctest --output-on-failure -R "ldc2-unittest"
      shell: ${{ inputs.shell }}
