name: Install LDC & make portable
inputs:
  arch:
    required: false # Windows only
  cross_compiling:
    required: false
    default: false
runs:
  using: composite
  steps:

    - name: Install LDC # into ../install/
      shell: bash
      run: |
        set -eux
        cd ..

        if [[ '${{ inputs.cross_compiling }}' != true ]]; then
          ninja -C build install >/dev/null
        else
          # the cross-compiled runtime libs have already been installed:
          # * lib/: runtime library artifacts
          # * etc/ldc2.conf/: 50-target-default.conf

          # now extend by installing the cross-compiled compiler:
          # * bin/: executables
          # * lib/: LTO plugin and compiler-rt libs
          # * etc/ldc2.conf/: 00-docs.conf, 30-compiler.conf, 55-target-wasm.conf, 70-compiler-rt.conf
          # * etc/bash_completion.d/
          # * import/: all runtime imports except for ldc/gccbuiltins_*.di
          ninja -C build-cross install

          # copy gccbuiltins from bootstrap compiler
          cp bootstrap-ldc/import/ldc/gccbuiltins_*.di install/import/ldc/
        fi

        cp ldc/LICENSE install/
        if [[ '${{ runner.os }}' == Windows ]]; then
          cp ldc/packaging/README.txt install/
        else
          cp ldc/packaging/README install/
        fi

    - name: 'Windows: Copy curl & MinGW-w64-based libs'
      if: runner.os == 'Windows'
      shell: bash
      run: |
        set -eux
        cd ..

        cp libcurl/ldc2/* install/bin/

        curl -fL --retry 3 --max-time 60 -o mingw-w64-libs.7z \
          https://github.com/ldc-developers/mingw-w64-libs/releases/download/v8.0.0/mingw-w64-libs-v8.0.0.7z
        mkdir mingw-w64-libs
        cd mingw-w64-libs
        7z x ../mingw-w64-libs.7z >/dev/null
        rm ../mingw-w64-libs.7z

        if [[ '${{ inputs.arch }}' == x86 ]]; then
          model=32
        else
          model=64
        fi
        cp -r "lib$model" ../install/lib/mingw
