name: Run defaultlib unittests & druntime integration tests
inputs:
  arch:
    required: true
runs:
  using: composite
  steps:

    - name: 'Posix: Run defaultlib unittests & druntime integration tests'
      if: runner.os != 'Windows'
      shell: bash
      run: |
        set -eux
        cd ../build
        if [[ '${{ runner.os }}' == macOS ]]; then
          N=$(sysctl -n hw.logicalcpu)
        else
          N=$(nproc)
        fi

        excludes="dmd-testsuite|lit-tests|ldc2-unittest"
        if [[ '${{ runner.os }}-${{ inputs.arch }}' == Linux-x86_64 ]]; then
          # sporadically hanging since Ubuntu 22
          excludes+='|^core.thread-shared_32$'
        elif [[ '${{ runner.os }}-${{ inputs.arch }}' == Linux-aarch64 ]]; then
          # FIXME: sporadically hanging
          excludes+='|^core.thread-shared$'
          if type -P apk &>/dev/null; then
            # FIXME: empty exception backtraces on musl AArch64 with enabled optimizations
            excludes+='|^druntime-test-exceptions-release$'
          fi
        fi
        if [[ '${{ runner.os }}' == macOS ]]; then
          # FIXME: https://github.com/dlang/phobos/issues/10730
          excludes+='|^std.experimental.allocator.building_blocks.allocator_list'
          if [[ '${{ inputs.arch }}' == x86_64 ]]; then
            # FIXME: regressed with image bump from macos-13 to macos-15-intel, apparently wrt. getpwnam_r() setting unexpected errno
            excludes+='|^std.path'
          fi
        fi

        ctest -j$N --output-on-failure -E "$excludes" --timeout 120

    - name: 'Windows: Run defaultlib unittests & druntime integration tests'
      if: runner.os == 'Windows'
      shell: cmd
      # temporarily set OS/MODEL & add druntime/Phobos/libcurl DLL dirs to PATH
      run: |
        echo on
        cd .. || exit /b
        set OS=windows
        if "${{ inputs.arch }}" == x86 (set MODEL=32) else (set MODEL=64)
        :: git's usr/bin/bash, unlike its bin/bash, leaves PATH as-is
        set "PATH=%CD%\build\lib;%CD%\libcurl\ldc2;C:\Program Files\Git\usr\bin;%PATH%"
        call "%LDC_VSDIR%\Common7\Tools\VsDevCmd.bat" -arch=${{ matrix.arch }} || exit /b
        echo on
        cd build || exit /b
        ctest -j4 --output-on-failure -E "dmd-testsuite|lit-tests|ldc2-unittest" --timeout 120 || exit /b
