# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Vanilla LLVM
on:
  - pull_request
  - push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-macos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: macOS 14, LLVM 17, latest LDC beta
            os: macos-14
            host_dc: ldc-beta
            llvm_version: 17.0.5
            cmake_flags: -DBUILD_SHARED_LIBS=ON -DRT_SUPPORT_SANITIZERS=ON -DD_COMPILER_FLAGS=-gcc=/usr/bin/c++ -DCMAKE_EXE_LINKER_FLAGS=-L/opt/homebrew/opt/zstd/lib
          - job_name: macOS 14, LLVM 16, latest LDC beta
            os: macos-14
            host_dc: ldc-beta
            llvm_version: 16.0.5
            cmake_flags: -DBUILD_SHARED_LIBS=OFF -DD_COMPILER_FLAGS=-gcc=/usr/bin/c++ -DCMAKE_EXE_LINKER_FLAGS=-L/opt/homebrew/opt/zstd/lib
          - job_name: macOS 11, LLVM 14, latest DMD beta
            os: macos-11
            host_dc: dmd-beta
            llvm_version: 14.0.6
            cmake_flags: -DBUILD_SHARED_LIBS=ON -DRT_SUPPORT_SANITIZERS=ON -DLDC_LINK_MANUALLY=ON -DCMAKE_CXX_COMPILER=/usr/bin/c++ -DCMAKE_C_COMPILER=/usr/bin/cc

    name: ${{ matrix.job_name }}
    runs-on: ${{ matrix.os }}
    env:
      # silence `ld: warning: object file (…) was built for newer macOS version (…) than being linked (…)`
      MACOSX_DEPLOYMENT_TARGET: ${{ matrix.os == 'macos-14' && '13.6' || '11.6' }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 50
      - name: Install ninja
        uses: symmetryinvestments/gha-setup-ninja@v1
      - name: Install D host compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.host_dc }}
      - name: Clear LD_LIBRARY_PATH to prevent loading host compiler libs
        run: echo "LD_LIBRARY_PATH=" >> $GITHUB_ENV
      - name: Install lit
        run: |
          set -euxo pipefail
          python3 -m pip install --user setuptools wheel
          python3 -m pip install --user lit
          python3 -c "import lit.main; lit.main.main();" --version . | head -n 1

      - name: Try to restore cached LLVM
        uses: actions/cache@v3
        with:
          path: llvm
          key: llvm-${{ matrix.llvm_version }}-${{ runner.os }}

      - name: Download & extract prebuilt vanilla LLVM ${{ matrix.llvm_version }}
        run: |
          set -eux
          if [[ -d llvm ]]; then
            echo "Already cached"
            exit 0
          fi
          version='${{ matrix.llvm_version }}'
          if [[ "$version" =~ ^1[6-9]\. ]]; then
            suffix='arm64-apple-darwin22.0'
          else
            suffix='x86_64-apple-darwin'
          fi

          url="https://github.com/llvm/llvm-project/releases/download/llvmorg-$version/clang+llvm-$version-$suffix.tar.xz"

          curl -fL --retry 3 --max-time 300 -o llvm.tar.xz "$url"
          mkdir llvm
          tar -xf llvm.tar.xz --strip 1 -C llvm
          rm llvm.tar.xz

          # don't link lib{c++,unwind} libs from LLVM package, they'd need RPATH fiddling
          if [[ '${{ runner.os }}' == macOS ]]; then
            rm -f llvm/lib/lib{c++,unwind}.*
          fi

      - name: Build LDC & LDC D unittests & defaultlib unittest runners with extra '${{ matrix.cmake_flags }}'
        run: |
          set -eux
          cmake -G Ninja . \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ROOT_DIR="$PWD/llvm" \
            -DLDC_LINK_MANUALLY=OFF \
            ${{ matrix.cmake_flags }}
          ninja obj/ldc2.o all ldc2-unittest all-test-runners
          bin/ldc2 --version

      - name: Run LDC D unittests
        if: success() || failure()
        run: ctest --output-on-failure -R "ldc2-unittest"
      - name: Run LIT testsuite
        if: success() || failure()
        run: ctest -V -R "lit-tests"
      - name: Run DMD testsuite
        if: success() || failure()
        run: ctest -V -R "dmd-testsuite"
      - name: Run defaultlib unittests & druntime integration tests
        if: success() || failure()
        run: |
          set -eux
          excludes='dmd-testsuite|lit-tests|ldc2-unittest'
          if [[ '${{ runner.os }}' == macOS ]]; then
            N=$(sysctl -n hw.logicalcpu)
            # FIXME: fails with enabled optimizations on M1 runners
            if [[ '${{ matrix.os }}' == macos-14 ]]; then
              excludes+='|^std.internal.math.gammafunction(-shared)?$'
            fi
          else
            N=$(nproc)
          fi
          ctest -j$N --output-on-failure -E "$excludes"
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - job_name: Ubuntu 20.04, LLVM 18, latest LDC beta
            os: 'ubuntu:20.04'
            host_dc: ldc-beta
            llvm_version: 18
          - job_name: Ubuntu 20.04, LLVM 15, latest LDC beta
            os: 'ubuntu:20.04'
            host_dc: ldc-beta
            llvm_version: 15
          - job_name: Ubuntu 20.04, LLVM 13, latest LDC beta
            os: 'ubuntu:20.04'
            host_dc: ldc-beta
            llvm_version: 13
            cmake_flags: -DRT_SUPPORT_SANITIZERS=ON
          - job_name: Ubuntu 20.04, LLVM 12, bootstrap LDC
            os: 'ubuntu:20.04'
            host_dc: ldc-1.19.0
            llvm_version: 12
            cmake_flags: -DBUILD_SHARED_LIBS=ON -DLIB_SUFFIX=64
          - job_name: Ubuntu 20.04, LLVM 11, latest DMD beta
            os: 'ubuntu:20.04'
            host_dc: dmd-beta
            llvm_version: 11
            cmake_flags: -DBUILD_SHARED_LIBS=OFF -DRT_SUPPORT_SANITIZERS=ON -DLDC_LINK_MANUALLY=ON
    name: ${{ matrix.job_name }}
    runs-on: ubuntu-22.04
    container: ${{ matrix.os }}
    steps:
      - name: 'Install base dependencies'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          set -eux
          apt-get update
          apt-get install -y wget git bash xz-utils build-essential python3-pip pkg-config
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 50
      - name: Install D host compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.host_dc }}
      - name: Clear LD_LIBRARY_PATH to prevent loading host compiler libs
        run: echo "LD_LIBRARY_PATH=" >> $GITHUB_ENV
      - name: Install lit
        shell: bash
        run: |
          set -euxo pipefail
          pip3 install -U setuptools wheel lit
          python3 -c "import lit.main; lit.main.main();" --version . | head -n 1
      - name: 'Linux: Install gdb and prebuilt vanilla LLVM ${{ matrix.llvm_version }}'
        shell: bash
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          set -eux
          source /etc/lsb-release
          DIST_SUITE="llvm-toolchain-$DISTRIB_CODENAME-${{ matrix.llvm_version }}"
          if [[ "$DISTRIB_CODENAME" == "focal" ]]; then
            wget https://apt.llvm.org/llvm-snapshot.gpg.key -qO /etc/apt/trusted.gpg.d/llvm.asc
            echo "deb https://apt.llvm.org/$DISTRIB_CODENAME/ ${DIST_SUITE} main" > /etc/apt/sources.list.d/llvm.list
          else
            sed -e "s|@DISTRO_SERIES@|${DISTRIB_CODENAME}|g" \
                -e "s|@DISTRO_SERIES_LLVM_VERSION@|${DIST_SUITE}|g" \
              "$PWD"/.github/workflows/apt-llvm-org.sources.in > /etc/apt/sources.list.d/apt-llvm-org.sources
          fi
          apt-get update
          apt-get install -y gdb "clang-${{ matrix.llvm_version }}" "lld-${{ matrix.llvm_version }}" cmake ninja-build
          if [[ "${{ matrix.llvm_version }}" -ge 13 ]]; then
            apt-get install -y "libmlir-${{ matrix.llvm_version }}-dev"
          fi

      - name: 'Linux: Make lld the default linker'
        if: matrix.host_dc != 'ldc-1.9.0'
        shell: bash
        run: |
          set -eux
          echo "Using lld to work around sporadic failures"
          ln -sf "ld.lld-${{ matrix.llvm_version }}" /usr/bin/ld
          ld --version

      - name: Build LDC & LDC D unittests & defaultlib unittest runners with extra '${{ matrix.cmake_flags }}'
        shell: bash
        env:
          CC: clang-${{ matrix.llvm_version }}
          CXX: clang++-${{ matrix.llvm_version }}
        run: |
          set -eux
          cmake -G Ninja . \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ROOT_DIR="/usr/lib/llvm-${{ matrix.llvm_version }}" \
            -DLDC_LINK_MANUALLY=OFF \
            ${{ matrix.cmake_flags }}
          ninja obj/ldc2.o all ldc2-unittest all-test-runners
          bin/ldc2 --version

      - name: Run LDC D unittests
        if: success() || failure()
        run: ctest --output-on-failure -R "ldc2-unittest"
      - name: Run LIT testsuite
        if: success() || failure()
        run: ctest -V -R "lit-tests"
      - name: Run DMD testsuite
        if: success() || failure()
        run: ctest -V -R "dmd-testsuite"
      - name: Run defaultlib unittests & druntime integration tests
        if: success() || failure()
        run: |
          set -eux
          excludes='dmd-testsuite|lit-tests|ldc2-unittest'
          ctest -j$(nproc) --output-on-failure -E "$excludes"
