# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Update DMD rewrite
on:
  schedule:
    - cron: "0 0 * * *"  # run every day at 00:00
  workflow_dispatch:  # enable manual runs

permissions:
  contents: write

jobs:
  update-dmd-rewrite:
    name: Update DMD rewrite
    if: github.repository == 'ldc-developers/ldc'  # don't run for forks
    runs-on: ubuntu-22.04
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: false
      - name: Install git-filter-repo v2.34.0
        run: |
          set -eux
          sudo apt-get -q update
          sudo apt-get install -yq git-filter-repo
      - run: tools/update-dmd-rewrite.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
